config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'
  resources :orders, only: [:index] do
      member do
        patch 'cancel'
      end
    end
  resources :rockets, only: [:index, :show] do
    resources :orders, only: [:new, :create]
  end

  namespace :owner do
    resources :orders, only: [:index] do
      collection do
        get 'index_json'
      end
      member do
        patch 'accept'
        patch 'decline'
        patch 'cancel'
      end
    end
    resources :rockets, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :rocket
  belongs_to :renter, class_name: 'User'

  validates :rocket, presence: true
  validates :renter, presence: true

  validates :begin_date, presence: true, allow_blank: false
  validates :end_date, presence: true, allow_blank: false

  validates :total_price, numericality: { only_integer: true }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
    @rocket = Rocket.new
  end

  def cancel
    @rocket = Rocket.new
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_path
  end

  def create
    @rocket = Rocket.find(params[:rocket_id])

    unless (order_params[:begin_date].empty? || order_params[:end_date].empty?)
      begin_date = Date.iso8601(order_params[:begin_date])
      end_date = Date.iso8601(order_params[:end_date])
      total_price = @rocket.daily_price * (end_date - begin_date).to_i
    end

    @order = Order.new(rocket_id: @rocket.id,
                       renter_id: current_user.id,
                       begin_date: begin_date,
                       end_date: end_date,
                       total_price: total_price)

    if @order.save
      redirect_to orders_path
    else
      redirect_to rocket_path(@rocket)
    end
  end

  private

  def order_params
    params.require(:order).permit(:begin_date, :end_date)
  end
end

app/controllers/owner/orders_controller.rb
class Owner::OrdersController < ApplicationController
  def index
    @orders = current_user.owner_orders.order(created_at: :asc)
  end

  def decline
    update_status('Declined')
  end

  def index_json
    @orders = current_user.owner_orders.order(created_at: :asc)
    @formatted_orders = @orders.map{ |order|
      {
        "title" => "#{User.find(order.renter_id).first_name} #{User.find(order.renter_id).last_name}",
        "start" => order.begin_date,
        "end" => order.end_date,

      }
    }
    render :json => @formatted_orders
  end

  def accept
    update_status('Accepted')
  end

  def cancel
    update_status('Pending')
  end

  private

  def update_status(new_status)
    @order = Order.find(params[:id])
    @order.status = new_status
    @order.save
    redirect_to owner_orders_path
  end
end

app/controllers/owner/rockets_controller.rb
class Owner::RocketsController < ApplicationController
  def index
    @rockets = current_user.rockets
  end

  def new
    @rocket = Rocket.new
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.owner = current_user
    if @rocket.save
      redirect_to rocket_path(@rocket)
    else
      render :new
    end
  end

  private

  def rocket_params
    params.require(:rocket).permit(:name, :daily_price, :autonomy, :photo, :address, :rooms_number, :beds_number, :bathrooms_number, :travellers_number, :surface, equipments:[])
  end
end

app/views/owner/orders/index.html.erb
<%= render 'shared/background' %>

  <div class='row mx-3'>

    <div class='col-7 p-0'>
      <!-- TITLE -->
      <div class='mx-auto w-100 text-center' style='height: 120px; position: sticky; top: 65px; z-index: 1;'>
        <h1 class='pt-3 pb-3 m-0 text-white'>My Rockets Requests</h1>
      </div>

      <div class='p' style='max-height: 75vh; overflow: scroll;'>
        <% @orders.each do |order| %>
          <!-- ORDER CARD -->
          <div class='card border-0 mx-auto my-3 container order-card' style='height: 200px; width: 90%;'>
            <div class='row h-100'>
              <!-- PICTURE PART -->
              <div class="card-category col-3 rounded-left" style="height: 100%; background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path order.rocket.photo.key, height: 300, width: 400, crop: :fill %>')">
                <h2 style='font-weight: lighter;'><%= order.rocket.name %></h2>
              </div>
              <!-- CONTENT PART -->
              <div class='col-6 p-3 d-flex flex-column justify-content-center' style='height: 200px;'>
                <div class='ml-3 d-flex flex-column justify-content-center'>
                  <div class='container'>
                    <div class="row">
                      <div class='col p-0'>
                        <p><span class='legend'>from</span><br/>
                          <%= order.begin_date.strftime("%d of %B, %Y") %></p>
                      </div>
                      <div class='col p-0'>
                        <p><span class='legend'>to</span><br/>
                          <%= order.end_date.strftime("%d of %B, %Y") %></p>
                      </div>
                    </div>
                    <div class='row d-flex align-items-center'>
                      <div>
                        <%= image_tag "pierre#{rand(1..9)}.jpg", class: "avatar1 mr-3", style: 'height: 55px; width:55px;'%>
                      </div>
                      <div>
                        <p class='name m-0'><%= order.renter.first_name %> <%= order.renter.last_name %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- PRICE PART -->
              <div class='col-3 p-2 d-flex justify-content-center align-items-center'>
                <div class='p-3 d-flex flex-column justify-content-center align-items-center'>
                  <p class='mb-4' style='font-size: 200%; font-weight: 800px;'>$<%= order.total_price %></p>
                  <% if order.status == 'Pending' %>
                  <!-- ACCEPT & DECLINE BUTTONS -->
                    <div class='d-flex flex-column'>
                      <%= link_to accept_owner_order_path(order), method: 'patch' do%>
                        <button type="button" class="btn btn-success mb-2" style='width: 90px;'>Accept</button>
                      <% end %>
                      <%= link_to decline_owner_order_path(order), method: 'patch' do%>
                        <button type="button" class="btn btn-outline-danger" style='width: 90px;'>Decline</button>
                      <% end %>
                    </div>
                  <% else %>
                  <!-- STATUS AND CANCEL BUTTON -->
                    <div class='d-flex flex-column align-items-center'>
                      <% if order.status == 'Accepted'%>
                        <p class='m-0 text-success'><%= order.status %></p>
                      <% else %>
                        <p class='m-0 text-danger'><%= order.status %></p>
                      <% end %>
                      <%= link_to cancel_owner_order_path(order), method: 'patch' do%>
                        <button type="button" class="btn btn-outline-dark mt-3" style='width: 90px;'>Cancel</button>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <!-- CALENDAR PART -->
    <div class='col-5 px-3 pt-0 pb-4 card my-3' style='background-color: white;'>
      <div id='calendar' class="margin-calendar" style="position: sticky; top: 110px;"></div>
    </div>


  </div>