config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'
  resources :orders, only: [:index] do
      member do
        patch 'cancel'
      end
    end
  resources :rockets, only: [:index, :show] do
    resources :orders, only: [:new, :create]
  end

  namespace :owner do
    resources :orders, only: [:index] do
      collection do
        get 'index_json'
      end
      member do
        patch 'accept'
        patch 'decline'
        patch 'cancel'
      end
    end
    resources :rockets, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_earth.html.erb
  <!-- Include the Web WorldWind library. -->
<script src="https://cdn.jsdelivr.net/npm/@nasaworldwind/worldwind@0.10.0/build/dist/worldwind.min.js"
    type="text/javascript"></script>
<%= javascript_pack_tag 'earth' %>

<div  class='w-100 p-5'> <!-- id="earthDiv" -->
  <!-- Create a canvas for Web WorldWind. -->
  <canvas id="canvasOne" class="rocket-card p-3">
    Your browser does not support HTML5 Canvas.
  </canvas>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <% if action_name == "home" %> navbar-home <% else %> navbar-allpages <% end %>" <% if action_name == "index" || action_name == "show"%> style="position: sticky; top: 0px; z-index: 1;" <% else %> style='z-index: 1;' <% end %>>
  <%= link_to homepage_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active border mr-3">
          <%= link_to "My Requests", orders_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item border mr-3">
          <%= link_to "My Rockets", "#", class: " request nav-link dropdown-toggle text-white", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add A New Rocket", new_owner_rocket_path, class: "dropdown-item" %>
            <%= link_to "List All", owner_rockets_path, class: "dropdown-item" %>
            <%= link_to "Requests Dashboard", owner_orders_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
            <%= image_tag "pierre10.jpg", class: " avatar nav-link dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>

        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: white"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>