config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'
  resources :orders, only: [:index] do
      member do
        patch 'cancel'
      end
    end
  resources :rockets, only: [:index, :show] do
    resources :orders, only: [:new, :create]
  end

  namespace :owner do
    resources :orders, only: [:index] do
      collection do
        get 'index_json'
      end
      member do
        patch 'accept'
        patch 'decline'
        patch 'cancel'
      end
    end
    resources :rockets, only: [:new, :create, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rocket.rb
require 'opencage/geocoder'

class Rocket < ApplicationRecord
  CONTINENT = ['Africa', 'Antarctica', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']
  EQUIPMENT = ['Wifi', 'Fitness room', 'Cinema', 'Jacuzzi', 'Spa', 'Booling', 'Golf court', 'Observatory', 'Horse riding', "Cocktail's bar", 'Skiing', 'Head cook']

  has_one_attached :photo
  belongs_to :owner, class_name: 'User'
  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  validate :manage_location
  validates :photo, presence: true
  validates :rooms_number, presence: true, numericality: { only_integer: true }
  validates :beds_number, presence: true, numericality: { only_integer: true }
  validates :bathrooms_number, presence: true, numericality: { only_integer: true }
  validates :travellers_number, presence: true, numericality: { only_integer: true }

  validates :owner, presence: true

  validates :daily_price, numericality: { only_integer: true }

  validates :name, presence: true, allow_blank: false
  validates :address, presence: true, allow_blank: false

  private
  def manage_location
    geocoder = OpenCage::Geocoder.new(api_key: ENV['OPENCAGE_KEY'])
    result = geocoder.geocode(self.address)
    unless result.empty?
      self.continent = result.first.components["continent"]
      self.country = result.first.components["country"]
      self.city = result.first.components["city"]
      self.latitude = result.first.lat
      self.longitude = result.first.lng
    else
      errors.add(:address, "Not a valid address")
    end
  end
end

app/controllers/owner/rockets_controller.rb
class Owner::RocketsController < ApplicationController
  def index
    @rockets = current_user.rockets
  end

  def new
    @rocket = Rocket.new
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.owner = current_user
    if @rocket.save
      redirect_to rocket_path(@rocket)
    else
      render :new
    end
  end

  private

  def rocket_params
    params.require(:rocket).permit(:name, :daily_price, :autonomy, :photo, :address, :rooms_number, :beds_number, :bathrooms_number, :travellers_number, :surface, equipments:[])
  end
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  def show
    @rocket = Rocket.find(params[:id])
    @order = Order.new
    @reviews = @rocket.reviews
    puts @ratings
  end

  # def index
  #   @rockets = Rocket.all
  # end

  def index
    @params = search_params
    @continent = @params[:continent]
    if !@params[:continent].empty?
      @rockets_init = Rocket.where(continent: @params[:continent])
    else
      @rockets_init = Rocket.all
    end

    @rockets = []
    @rockets_init.each do |rocket_init|
      @rockets << rocket_init
    end

    search_begin_date = @params[:begin_date]
    search_end_date = @params[:end_date]

    if (search_begin_date.empty? || search_end_date.empty? || search_begin_date == 'From' || search_end_date == 'To')
      search_begin_date = nil
      search_end_date   = nil
    else
      search_begin_date = Date.iso8601(search_begin_date)
      search_end_date   = Date.iso8601(search_end_date)
    end

    unless search_begin_date.nil? || search_end_date.nil?
      @rockets.each do |rocket|
        unless rocket.orders.empty?
          rocket.orders.each do |order|
            if order.status == 'Accepted'
              unless (order.begin_date < search_begin_date && order.end_date < search_begin_date) || (order.begin_date > search_end_date && order.end_date > search_end_date)
                @rockets.delete(rocket)
              end
            end
          end
        end
      end
    end
    @rockets
  end

  private

  def search_params
    params.require(:search).permit(:continent, :begin_date, :end_date)
  end
end

app/views/rockets/index.html.erb
<%= render 'shared/background' do %>
<%= content_tag :div, class: "continent", data: {continent: @continent} do %>
<% end %>
<div class="container">
  <div class='row d-flex justify-content-between my-3'>
    <h1 class = "mb-3 text-align-center" id='neon-title'>RocketMan</h1>
    <div class='m-auto'>
      <%= simple_form_for :search, url: rockets_path, method: "GET",
        wrapper: :inline_form,
        html: { class: "form-inline" },
        wrapper_mappings: {
          boolean: :inline_boolean
        }  do |f| %>
        <%= f.input :continent, collection: Rocket::CONTINENT, prompt: @params[:continent], input_html: {class: "mb-2 mr-sm-2"} %>
        <%= f.input :begin_date, as: :string, required: false, input_html: {value: @params[:begin_date], class: "datepicker mb-2 mr-sm-2"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {value: @params[:end_date], class: "datepicker mb-2 mr-sm-2"}  %>
        <%= button_tag( :class => "btn btn-primary mb-2") do %>
          TAKE OFF <i class="fas fa-space-shuttle"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-5" style="max-height: 75vh; overflow: scroll;">
      <% @rockets.each do |rocket| %>
          <div class="rocket-card mt-3 mb-3" data-longitude="<%= rocket.longitude %>" data-latitude="<%= rocket.latitude %>" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path rocket.photo.key %>')">
            <div class="card-category card-description d-flex flex-column mt-auto mb-3">
              <div class="rocket-card-title  text-align-center pt-3">
                <h1 style = "color: white"><%= rocket.name %></h1>
              </div>
              <div class="flex text-align-center pb-3">
                <h6 style = "color: white"><%= rocket.city %>, <%= rocket.country %></h6>
              </div>
            </div>
            <%= link_to 'More info', rocket_path(rocket), target: :_blank, class: "card-link"%>
          </div>

      <% end %>
    </div>
    <div class="col-7" style="position: sticky; right: 100px;">
        <%= render 'shared/earth' %>
    </div>

  </div>
</div>
<% end %>

app/views/rockets/show.html.erb
<%= render 'shared/background' %>

<div class ="row visible">

  <div class="col-12 col-md-6" style='height: calc(100vh - 65px); position: sticky; top: 65px;'>
    <div class='row' style='height: 65%;'>
      <div class='d-flex align-items-end' style="width:100%; background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @rocket.photo.key %>')">
        <div class='mx-5 my-3 text-white'>
          <h1 class='title-text'><strong><%= @rocket.name %></strong></h1>
          <p class='subtitle-text'>Launch form <%= @rocket.city %>, <%= @rocket.country %></p>
        </div>
      </div>
    </div>
    <div class='row' style='height: 35%;'>
      <div class='' style="width:50%; background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('https://live.staticflickr.com/65535/47706292911_b8370310a1_b.jpg')"></div>
      <div class='' style="width:50%; background-size: cover; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('https://cdn.images.express.co.uk/img/dynamic/151/590x/secondary/NASA-news-space-station-pictures-Earth-from-space-International-Space-Station-ISS-1951450.jpg?r=1562686066683')"></div>
    </div>
  </div>

  <div class="col-12 col-md-6 p-3">

    <div class="card p-3 m-3">
      <div class='row'>
        <div class='col-6'>
          <%= simple_form_for [@rocket, @order] do |f| %>
            <%= f.input :begin_date, as: :string, input_html: {class: "begin_date datepicker"} %>
            <%= f.input :end_date, as: :string, input_html: {class: "end_date datepicker"} %>
        </div>
        <div class='col-6 d-flex flex-column justify-content-between p-3'>
            <div class= "mr-3">
              <div class='d-flex justify-content-between border-bottom pb-2'>
                <p class='m-0 text-secondary'>details</p>
                <p class = "m-0" id = "calcul" data-dailyPrice="<%= @rocket.daily_price %>">$<%= @rocket.daily_price %> x 0 days</p>
              </div>
              <div class='d-flex justify-content-between align-items-end mt-2'>
                <p class='m-0 text-secondary'>total price</p>
                <p class = "m-0" id="price" style='font-size: 200%;'>$0</p>
              </div>
            </div>
            <%= f.submit "I book!", class: "btn btn-info" %>
        </div>
          <% end %>
      </div>
    </div>

    <div class="card p-3 m-3">

      <div class='d-flex justify-content-between align-items-center m-3'>
        <div class='m-0 p-0'>
          <h4>A unique rocket!</h4>
          <p>

          <div class="stars">
          <% if @reviews.size > 0 %>
            <% average = 0
            total = @reviews.each { |review| average += review.rating }
            average = average / @reviews.size %>
            <% average.to_i.times do  %>
              <span class="fa fa-star checked"></span>
            <% end %>
            <% other_stars_number = 5 - average.to_i %>
            <% other_stars_number.times do  %>
              <span class="fa fa-star"></span>
            <% end %>
            <% else %>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
            <p>No review for this rocket</p>

            <% end %>
          </div>
          <a href="#">Add a review</a>
          </p>

          <div>
            <p class='m-0'>
              <%= @rocket.travellers_number %> <%= @rocket.travellers_number == 1 ? 'traveller' : 'travellers' %> ·
              <%= @rocket.beds_number %> <%= @rocket.beds_number == 1 ? 'bed' : 'beds' %> ·
              <%= @rocket.rooms_number %> <%= @rocket.rooms_number == 1 ? 'room' : 'rooms' %> ·
              <%= @rocket.bathrooms_number %> <%= @rocket.bathrooms_number == 1 ? 'bathroom' : 'bathrooms' %>
            </p>
          </div>
        </div>
        <div>
          <%= @rocket.owner.first_name %><%= image_tag "pierre.jpg", class: "avatar1 mx-3" %>
        </div>
      </div>

      <div class="d-flex flex-wrap py-4 m-3 border-bottom border-top">

        <%if @rocket.equipments.include?("Wifi")%><div class='equipment'><i class="fas fa-wifi mr-3"></i> Wifi </br></div><%end%>
        <%if @rocket.equipments.include?("Fitness room")%><div class='equipment'><i class="far fa-heart mr-3"></i> Fitness room </br></div><%end%>
        <%if @rocket.equipments.include?("Cinema")%><div class='equipment'><i class="fas fa-film mr-3"></i> Cinema </br></div><%end%>
        <%if @rocket.equipments.include?("Jacuzzi")%><div class='equipment'><i class="fas fa-hot-tub mr-3"></i> Jacuzzi </br></div><%end%>
        <%if @rocket.equipments.include?("Spa")%><div class='equipment'><i class="fas fa-spa mr-3"></i> Spa </br></div><%end%>
        <%if @rocket.equipments.include?("Booling")%><div class='equipment'><i class="fas fa-bowling-ball mr-3"></i> Booling</div><%end%>
        <%if @rocket.equipments.include?("Golf court")%><div class='equipment'><i class="fas fa-golf-ball mr-3"></i> Golf court</div><%end%>
        <%if @rocket.equipments.include?("Observatory")%><div class='equipment'><i class="fas fa-binoculars mr-3"></i> Observatory </br></div><%end%>
        <%if @rocket.equipments.include?("Horse riding")%><div class='equipment'><i class="fas fa-horse-head mr-3"></i></i> Horse riding</div><%end%>
        <%if @rocket.equipments.include?("Cocktail's bar")%><div class='equipment'><i class="fas fa-cocktail mr-3"></i> Cocktail's bar</div><%end%>
        <%if @rocket.equipments.include?("Skiing")%><div class='equipment'><i class="fas fa-skiing mr-3"></i> Skiing</div><%end%>
        <%if @rocket.equipments.include?("Head cook")%><div class='equipment'><i class="fas fa-utensils mr-3"></i> Head cook</div><%end%>

      </div>

      <div class='p-3'>
        <p class='m-0'>Nous avons eu un véritable coup de cœur pour cet appartement vue sur l'île de Nantes et son éléphant. Idéal pour visiter Nantes au calme en regardant passer les bateaux, vous êtes les bienvenus. Ancien appartement Nantais rénové en pierre.</p>
      </div>
    </div>
    <div class="card p-3 m-3">
      <% @reviews.each do |review| %>
      <div>
        <% review.rating.to_i.times do  %>
          <span class="fa fa-star checked"></span>
        <% end %>
        <% other_stars_number = 5 - review.rating.to_i %>
        <% other_stars_number.times do  %>
          <span class="fa fa-star"></span>
        <% end %>
      </div>
        <p><%= review.description %></p>
        <br>
      <% end %>
    </div>

</div>

<%= javascript_pack_tag 'calculate_booking_price' %>